# hash:sha256:ef9fbb3ba89fab8e51c55da42942782892acea557c84efada3ff709847a272f3
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/code-server-python-extensions-pack:v5.0

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
